name: BosterItemSpawner
main: net.Boster.item.spawner.BosterItemSpawner
author: Bosternike
version: 1.0.0
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  bosteritemspawner:
    aliases: [bis]