name: BosterItemSpawner
main: net.Boster.item.spawner.BosterItemSpawner
author: Bosternike
version: 1.0.1
api-version: 1.13
depend: [HolographicDisplays]
softdepend: [PlaceholderAPI]
commands:
  bosteritemspawner:
    aliases: [bis]